### ISSUE TITLE
[FR] Support Mollie Subscriptions

### ISSUE THREAD

**Issue by shoored** [studioespresso/craft-mollie-payments#1]
First of all, great plugin! Sorry to have a FR the day after launch, but is Mollie Recurring on the roadmap by any chance? 

I read on the P&T Mollie plugin that they will not be implementing subscriptions with Mollie Recurring. Could be great for European customers to have this feature.

**Comment by janhenckens** [comment]
Nothing to be sorry about 😉
It's on my list of things to investigate but haven't used that part of the API before so I'm not sure how I'll implement it yet. 

Also still trying out the plugin as a beta on a project so if you have other requests or issues, feel free to send them along :)

**Comment by pimago** [comment]
Hell Jan, any plans to add subscriptions? So the plugin could be used to build a paid membership site.

**Comment by janhenckens** [comment]
Finally added this in the latest Craft 5 version - docs can be found here https://studioespresso.github.io/craft-mollie-payments/subscription-getting-started.html
