### ISSUE TITLE
[FR] Api key per site

### ISSUE THREAD

**Issue by bartrylant** [studioespresso/craft-mollie-payments#12]
It would be nice if we could use an api key per website on a multisite install. Right now I'm using this plugin on two websites that share the same shop. The Mollie payment interface is linked to the api key, so at the moment I have to show the same interface on both websites. It would be nice if every website could set its own api key for Mollie and thus use it's own Mollie interface.

**Comment by janhenckens** [comment]
Hey Bart,
I finally got around to adding this, updated to the docs on how to do this here https://studioespresso.github.io/craft-mollie-payments/settings.html
