### ISSUE TITLE
2.0.0 does not properly support project config

### ISSUE THREAD

**Issue by boboldehampsink** [studioespresso/craft-mollie-payments#26]
It still references the field layout by id in stead of uid, and it doesn't save the field layout itself to project config.

**Comment by janhenckens** [comment]
Hey Bob, I'll try to get this fix asap. Didn't know the project config should also include the field layout itself.

**Comment by janhenckens** [comment]
Fixed in 2.0.1.

**Comment by boboldehampsink** [comment]
Thanks! Can you tag it on GitHub so Packagist picks it up?
