### ISSUE TITLE
Support for refunds

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft-mollie-payments#28]
Is it possible to add a refund status?

![Screen Shot 2021-03-17 at 12 39 03](https://user-images.githubusercontent.com/42932673/111468187-9186c380-8725-11eb-84e7-6311cdc708c4.png)

![Screen Shot 2021-03-17 at 12 38 46](https://user-images.githubusercontent.com/42932673/111468196-92b7f080-8725-11eb-819f-176ee244f1b7.png)

**Comment by janhenckens** [comment]
Fixed this in 2.1.0. You'll want to add an extra check to the `afterTransactionUpdateEvent` and listen for the "refunded" status.
