### ISSUE TITLE
Multi-step form isn't working anymore

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft-mollie-payments#29]
We did an update from this plugin and the Multi-step form isn't working anymore.

We get errors on this **fields**:
```
$payment->email = '';
$payment->amount = $amount;
```

In the **PaymentController.php actionDonate()**: the form is defined by **ID** instead of **Handle**

The **redirect** after this function is also not working.

Could you check this please?
Thank you!

**Comment by janhenckens** [comment]
Fixed in 2.1.2
