### ISSUE TITLE
403 error on confirmation page redirection

### ISSUE THREAD

**Issue by byTwinn** [studioespresso/craft-mollie-payments#32]
Hello, I'm testing your plugin on our website. 
All is fine, form, data sent to mollie, the transactions all also well recorder in craft but the redirection to confirmation page is not working. I have a 403 error. ("Request forbidden by administrative rules.")

The weird part is if I click on URL address bar on my browser and push enter to reload the confirmation page is well displayed.

Do you have an idea to help me ? Thanks

Matthieu

**Comment by janhenckens** [comment]
Hey @byTwinn , could you share what the redirect url looks like? And maybe a screenshot of the error message?
Thanks

**Comment by byTwinn** [comment]
hello @janhenckens Thanks for your help.

The url is : https://craft3-eba49cee1ba6.hyperlane.co/be-fr/mollie-payments/payment/redirect?order_id=71e0e942-b308-410a-82ed-7dba0eae7896&redirect=https%3A//craft3-eba49cee1ba6.hyperlane.co/be-fr/confirmation

Here, the screenshot
<img width="329" alt="Capture d’écran 2021-05-17 à 14 53 51" src="https://user-images.githubusercontent.com/254524/118491951-cad8b100-b71f-11eb-877a-32a4a666f983.png">

**Comment by janhenckens** [comment]
Hmm, that works when I visit the full return url and when I visit just the redirect url.
The error message itself is thrown by the webserver so your best bet is to check those logs to see what is causing the error.

**Comment by byTwinn** [comment]
thanks @janhenckens, I checked and I think it's a setting of our dev server. In production All is fine :-)
