### ISSUE TITLE
form not found (multi-step form)

### ISSUE THREAD

**Issue by byTwinn** [studioespresso/craft-mollie-payments#33]
Hello (again),

I have successfully implemented a one step form with you documentation but for the multi-level I received an error message.

"Invalid Configuration – yii\base\InvalidConfigException

Form not found"

The problem line seams to be :  $paymentForm = MolliePayments::getInstance()->forms->getFormByid($form);

I double-checked the $form var and it is the good form handle (bundle)...

You can try here, just push the "pay button" : https://craft3-eba49cee1ba6.hyperlane.co/be-fr/action/product

Thanks again for your help

Matthieu

**Comment by janhenckens** [comment]
Hey Matthieu

Looks like the docs got a bit out of sync with the recent changes, sorry about that. 
I've updated them here https://studioespresso.github.io/craft-mollie-payments/template.html#multi-step-form
Can you compare with what you have right now and change where needed? 

Let me know how you get on with it after this!
Jan
