### ISSUE TITLE
Webhook fails with Bad Request

### ISSUE THREAD

**Issue by boboldehampsink** [studioespresso/craft-mollie-payments#54]
Webhook always fails with message "Webhook failed with status code 400 (Bad Request)" - because it is missing the required param "id" 

The webhook url in the generatePayment function should probably be updated to include id?

**Comment by janhenckens** [comment]
The webhook is a POST request to `/mollie-payments/payment/webhook`, with the payment ID in the request body (eg `id= tr_kRZSRUwBEJ`).

Are you seeing this error in production? We have the current code running on multiple sites and are not seeing this issue.

**Comment by boboldehampsink** [comment]
@janhenckens problem is it didn't send the id. I created a PR that fixes this: #55

**Comment by janhenckens** [comment]
Your PR adds the ID for the payment element in Craft but we actually need the ID of the payment on Mollie's side, which we don't have yet since we're still creating the payment at that point so there is no way to ID (which doesn't exist yet) to the url.

Is this a one-off with a specific payment or are you seeing this regularly in production?

**Comment by boboldehampsink** [comment]
Mmm ok. I'm seeing this regularly for every payment in production...

**Comment by janhenckens** [comment]
Hmm, weird. Which version of Craft are you running?

**Comment by boboldehampsink** [comment]
3.7.47.1

**Comment by janhenckens** [comment]
That won't be it then.
First off, here's an example of how the web hook request looks https://docs.mollie.com/overview/webhooks

Assuming Mollie is sending it, is there something in the (web)server setup for  this specific project that might be causing the issue? (apache or ngnix config, special redirect, ...)

**Comment by boboldehampsink** [comment]
Mmm I have Snaptcha set up. I'm guessing that might be it! I had excluded the `donate` and `pay` actions already but not `webhook`! Let's see if that fixes it ;-)

**Comment by boboldehampsink** [comment]
Fixed now! Thanks

**Comment by janhenckens** [comment]
Good to hear! Thanks for letting me know :)
