### ISSUE TITLE
[FR] Display custom form fields in template

### ISSUE THREAD

**Issue by bartrylant** [studioespresso/craft-mollie-payments#6]
It would be nice if there was a way to show custom form fields in a template. E.g. based on the long order id that gets returned by Mollie. This would make it possible to show order details that are stored in the database, on the final confirmation page.

**Comment by janhenckens** [comment]
Hey Bart, good idea! That should be quite easy to do. I'll get back to you shortly 🙂

**Comment by janhenckens** [comment]
Hey @bartrylant 
Just released an update that includes this, you can find the docs here: https://studioespresso.github.io/craft-mollie-payments/template.html
