### ISSUE TITLE
Link to Payment detail in backend does not work anymore

### ISSUE THREAD

**Issue by HannahDeWachter** [studioespresso/craft-mollie-payments#61]
It is not possible to click on a payment in the backend.
<img width="1192" alt="Screenshot 2023-01-13 at 14 49 26" src="https://user-images.githubusercontent.com/55497252/212335252-6aefc2c8-bd1d-46f0-a336-9a4574589fce.png">

**Comment by janhenckens** [comment]
Hey @HannahDeWachter, this was fixed in today's release!
