### ISSUE TITLE
The documentation is no longer working

### ISSUE THREAD

**Issue by bartdigitalpulse** [studioespresso/craft-mollie-payments#64]
The css and javascript files are missing.

https://studioespresso.github.io/craft-mollie-payments/

**Comment by byTwinn** [comment]
Hello !
Is there any news about this issue?

Thanks

**Comment by janhenckens** [comment]
hey @byTwinn @bartdigitalpulse, I'm in the process of moving and am without internet until next week. You can find the content of the docs here in the meantime https://github.com/studioespresso/craft-mollie-payments/tree/develop/docs. 

I'll keep you posted when I get it fixed!

**Comment by janhenckens** [comment]
Finally got around to debugging this and it's fixed now!
