### ISSUE TITLE
Both tabs are highlighted when viewing a payment in CP

### ISSUE THREAD

**Issue by shoored** [studioespresso/craft-mollie-payments#68]
When viewing a payment in the Craft Control Panel, both the tab with my custom fields as well as "Transactions" are active. Only when selecting either tab is this corrected.

Initial state when a payment loads:
<img width="386" alt="image" src="https://github.com/studioespresso/craft-mollie-payments/assets/26165948/c8b67e02-f09f-4568-a87f-392a0bae7904">

**Comment by janhenckens** [comment]
Hey @shoored, which version of Craft & of the plugin are you running?

This is how it looks on my end:
![Screenshot 20231227-103022-OWgKgo6a](https://github.com/studioespresso/craft-mollie-payments/assets/755428/2f8dcddb-9d57-4876-a96a-3151f4369884)

Checking the source, the first tab is set as selected, the second is not.

**Comment by shoored** [comment]
Hey @janhenckens thanks for checking this out. 

Strangely enough, it does look okay on production, just not on my local ddev environment. Both Tabs (`a` in the `li`) get a `sel` class.

I'm running on
Craft 3.9.6
Payments 2.2.3

Planning to upgrade this week though.

**Comment by janhenckens** [comment]
That's strange - though I didn't go back to check in Craft 3.
I'll close the issue for now, feel free to reopen if you're still seeing the problem on Craft 4.

**Comment by shoored** [comment]
It's all good on Craft 4!
