### ISSUE TITLE
Mollie Status other than 'paid' not working

### ISSUE THREAD

**Issue by kevinmu17** [studioespresso/craft-mollie-payments#70]
When checking payment failed and submit in the Mollie test screen, you get redirected back to the option page from mollie again.

I expect this to track the failed payment in the plugin. But it instantly retries the payment. The only option to continue is to set it to paid. 

Is there an option to make the plugin not instant retry but to save the failed payment status?

**Comment by janhenckens** [comment]
Are you seeing this in test mode only @kevinmu17? I see the same behaviour but it's not the plugin retrying the same payment, that's mollie's behaviour I think.

**Comment by kevinmu17** [comment]
Yes, I'm using the mollie test api key. But in comparison with craft commerce + a mollie plugin, the status is returning to the website. So when selecting iDeal payment and set it to failed, it gets you back to the website with this status.

Heres a screenshot of the history change within mollie:
<img width="276" alt="Screenshot 2024-07-01 at 13 42 16" src="https://github.com/studioespresso/craft-mollie-payments/assets/8747373/4995a915-ec86-4795-9eda-3cffd5a6fd8e">

I'm not quite sure if its mollie reopening the payment because i have another local setup with craft commerce (also in test mode) that doesn't show this behaviour.

**Comment by kevinmu17** [comment]
Allright, I came across this github issue https://github.com/mollie/laravel-mollie/issues/113 where they explain this situation. Because there are multiple payment options this is 'correct' behaviour. So it's not the plugin, closing it ;)

**Comment by janhenckens** [comment]
Thanks, didn't know that yet :)

**Comment by kevinmu17** [comment]
For future readers. To test every scenario, set your mollie account to one payment method (for example, only activate iDeal). This way you can test your application with all the other statuses reaching back to your site ;) _tested_
