### ISSUE TITLE
[FR] support for project.yaml

### ISSUE THREAD

**Issue by bartrylant** [studioespresso/craft-mollie-payments#8]
At the moment project.yaml is not supported.

**Comment by janhenckens** [comment]
Hey Bart
Would like the save the plugins settings? Of the forms you created as well?

Thanks
Jan

**Comment by bartrylant** [comment]
It would be nice if you could sync the forms with project.yaml. So yo can create a new form on dev and sync it with staging.

**Comment by janhenckens** [comment]
Gotcha, just like you would with sections & entry types. I’ll have a look at how that could work but it should be possible.

**Comment by studiosyntax** [comment]
Currently indeed the forms created locally do not get synced to other environments, but I'm also not able to create new forms on an environment where `allowAdminChanges` is set to `false`. Any suggestions on the workflow to be used?

**Comment by janhenckens** [comment]
This is out in 2.0.0
